// micro-app-react/src/pages/list/index.jsx
// eslint-disable-next-line
import React, { useState, useEffect } from "react";
// eslint-disable-next-line
import { Card, Table, Avatar } from "antd";
// eslint-disable-next-line
import fetch from "isomorphic-fetch";

// const fetchVegetable = () => {
//   return fetch("http://localhost:3000/vue/list", {
//     method: "GET",
//     headers: {
//       "Content-Type": "application/json",
//     },
//     // graphql 的查询风格
//     // body: JSON.stringify({
//     //   query: `{ vegetableList (page: ${page}, pageSize: ${pageSize}) { page, pageSize, total, items { _id, name, poster, price } } }`,
//     // }),
//     //
//   }).then((res) => res.json());
// };

// const { Column } = Table;
// const List = () => {
//   // 设置列表信息
//   const [data, setData] = useState([]);
//   // 设置页码信息
//   const [page, setPage] = useState(1);
//   const [pageInfo, setPageInfo] = useState();

  

//   return (
//     <Card title="React 子应用列表页">
//       <Table rowKey="_id" dataSource={data} pagination={pageInfo}>
//         <Column dataIndex="poster" render={(text) => <Avatar src={text} />} />
//         <Column dataIndex="name" />
//         <Column dataIndex="price" render={(text) => <>￥ {text}</>} />
//       </Table>
//     </Card>
//   );
// };


const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
  },
];

// const data = [
//   {
//     key: '1',
//     name: 'John Brown',
//     age: 32,
//     address: 'New York No. 1 Lake Park',
//   },
//   {
//     key: '2',
//     name: 'Jim Green',
//     age: 42,
//     address: 'London No. 1 Lake Park',
//   },
//   {
//     key: '3',
//     name: 'Joe Black',
//     age: 32,
//     address: 'Sidney No. 1 Lake Park',
//   },
// ];

const List = () => {
  const [data, setData] = useState();
  useEffect(() => {
    fetch('http://localhost:3000/react/list')
    .then(function(response) {
      return response.json();
    })
    .then(function(myJson) {
      console.log(myJson.data);
      if(myJson.data){
        setData(myJson.data)
        console.log("11111")
      }
      // 
    });
  }, true);
  
  return(
    <Card title="React 子应用列表页">
      <Table columns={columns} dataSource={data} />
    </Card>
  )
}

export default List;

// micro-app-vue/src/pages/list/index.vue
<template>
  <section>
    <a-card title="Vue 微应用列表页">
      <a-table :columns="columns" :data-source="tabledata">
        <a slot="name" slot-scope="text">{{ text }}</a>
        <span slot="customTitle"> Name</span>        
      </a-table>
    </a-card>
  </section>
</template>

<script>
import fetch from "isomorphic-fetch";

const columns = [
  {
    dataIndex: 'name',
    key: 'name',
    slots: { title: 'customTitle' },
    scopedSlots: { customRender: 'name' },
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
  },
];
// const tabledata = [];
export default {
  name: "List",
  data() {
    return {
      tabledata:[],
      columns,
    }
  },

  mounted(){
    const that = this;
    fetch('http://localhost:3030/vue/list')
    .then(function(response) {
      return response.json();
    })
    .then(function(myJson) {
      console.log(myJson); 
      that.tabledata = myJson.data;
    });
  },
  
  methods: {
    // async fetchVegetable () {
    //   const result = await fetch("http://localhost:3000/vue/list", {
    //     method: 'GET',
    //     headers: {
    //       'Content-Type': 'application/json'
    //     },
    //     // graphql 的查询风格
    //     // body: JSON.stringify({ query: `{ vegetableList (page: ${page}, pageSize: ${pageSize}) { page, pageSize, total, items { _id, name, poster, price } } }` })
    //   }).then(res => res.json());
    //   console.log(result)
      // const { vegetableList } = result.data;
      // this.data = vegetableList.items;
      // this.pageInfo = {
      //   current: vegetableList.page,
      //   pageSize: vegetableList.pageSize,
      //   total: vegetableList.total,
      //   onChange: page => this.fetchVegetable(page, 10)
      // };
    // }
  },

  // created() {
  //   this.fetchVegetable(1, 10);
  // }
}
</script>
